/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOMYBW1
#define ROOMYBW1

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class RooMyBW1 : public RooAbsPdf {
public:
  RooMyBW1() {} ; 
  RooMyBW1(const char *name, const char *title,
	      RooAbsReal& _m_phi_etap,
	      RooAbsReal& _mean,
	      RooAbsReal& _Gamma);
  RooMyBW1(const RooMyBW1& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooMyBW1(*this,newname); }
  inline virtual ~RooMyBW1() { }

protected:

  RooRealProxy m_phi_etap ;
  RooRealProxy mean ;
  RooRealProxy Gamma ;
  
  Double_t evaluate() const ;

private:

  ClassDef(RooMyBW1,1) // Your description goes here...
};
 
#endif
