/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOMYBW2
#define ROOMYBW2

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class RooMyBW2 : public RooAbsPdf {
public:
  RooMyBW2() {} ; 
  RooMyBW2(const char *name, const char *title,
	      RooAbsReal& _m_phi_etap,
	      RooAbsReal& _mean,
	      RooAbsReal& _Gamma);
  RooMyBW2(const RooMyBW2& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooMyBW2(*this,newname); }
  inline virtual ~RooMyBW2() { }

protected:

  RooRealProxy m_phi_etap ;
  RooRealProxy mean ;
  RooRealProxy Gamma ;
  
  Double_t evaluate() const ;

private:

  ClassDef(RooMyBW2,1) // Your description goes here...
};
 
#endif
