/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOMYSIG
#define ROOMYSIG

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class RooMySig : public RooAbsPdf {
public:
  RooMySig() {} ; 
  RooMySig(const char *name, const char *title,
	      RooAbsReal& _m,
	      RooAbsReal& _mean,
	      RooAbsReal& _Gamma,
	      RooAbsReal& _phi,
	      RooAbsReal& _ratio,
	      RooAbsReal& _p1,
	      RooAbsReal& _p2,
	      RooAbsReal& _p3,
	      RooAbsReal& _p4,
	      RooAbsReal& _p5,
	      RooAbsReal& _p6);
  RooMySig(const RooMySig& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooMySig(*this,newname); }
  inline virtual ~RooMySig() { }

protected:

  RooRealProxy m ;
  RooRealProxy mean ;
  RooRealProxy Gamma ;
  RooRealProxy phi ;
  RooRealProxy ratio ;
  RooRealProxy p1 ;
  RooRealProxy p2 ;
  RooRealProxy p3 ;
  RooRealProxy p4 ;
  RooRealProxy p5 ;
  RooRealProxy p6 ;
  
  Double_t evaluate() const ;

private:

  ClassDef(RooMySig,1) // Your description goes here...
};
 
#endif
